### ISSUE TITLE
LifecycleOwner com.digio.digo_core.MainActivity@aa5adcd is attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED.

### ISSUE THREAD

**Issue by digioAbhi** [digio-tech/gateway#6]
```
java.lang.IllegalStateException: LifecycleOwner com.digio.digo_core.MainActivity@aa5adcd is attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED.
                                                                                                    	at androidx.activity.result.ActivityResultRegistry.register(ActivityResultRegistry.kt:93)
                                                                                                    	at androidx.activity.ComponentActivity.registerForActivityResult(ComponentActivity.kt:828)
                                                                                                    	at androidx.activity.ComponentActivity.registerForActivityResult(ComponentActivity.kt:837)
                                                                                                    	at in.digio.sdk.gateway.Digio.initLauncher(Digio.kt:60)
                                                                                                    	at in.digio.sdk.gateway.Digio.initSession(Digio.kt:52)
                                                                                                    	at com.digio.digo_core.FragmentTestFragment.onCreate(FragmentTestFragment.kt:30)
                                                                                                    	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3095)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:516)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:274)
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2103)
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1998)
                                                                                                    	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1941)
                                                                                                    	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:661)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7948)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
                                                                                                    	```

**Comment by digioAbhi** [comment]
call 
digio.initSession(requireActivity(), this)
in the oncreate of the activity
